name: Build Todd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: 
    - uses: egor-tensin/setup-gcc@v1.3
      with:
        platform: x86
    - name: make
      run: make

