name: Build Todd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: 
    - uses: egor-tensin/setup-gcc@v1.3
      with:
        platform: x86
    - uses: awalsh128/cache-apt-pkgs-action@v1.4.2
      with:
        packages: libncurses5-dev
        version: "1.0"
    - name: make
      run: make

