name: Build Todd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libncurses5-dev
        version: "1.0"
    - name: make
      run: make
    - name: copy to build folder
      run: |
        mkdir -p build
        cp ./todd build/
    - uses: actions/upload-artifact@v4
      with:
        name: todd-linux
        path: build

  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: copy to build folder
      run: |
        mkdir -p build
        cp ./todd build/
    - uses: actions/upload-artifact@v4
      with:
        name: todd-mac
        path: build
